Description: "bjw.me.uk domain"
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  hostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: bjw.me.uk

  mxRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: MX
      TTL: 500
      ResourceRecords:
      - "10 mx01.mail.icloud.com."
      - "20 mx02.mail.icloud.com."

  txt1RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: TXT
      TTL: 900
      ResourceRecords:
      - "\"apple-domain=uwUDTXsq8P0ljHhS\""
      - "\"v=spf1 include:icloud.com ~all\""

  caaLetsEncryptRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: CAA
      TTL: 900
      ResourceRecords:
      - "0 issue \"letsencrypt.org\""
      - "0 issue \"amazon.com\""

  blogRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: blog.bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: CNAME
      TTL: 900
      ResourceRecords:
      - "ghs.google.com."

  cname0RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: ruznjgag3ou2.bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: CNAME
      TTL: 900
      ResourceRecords:
      - "gv-otj7ogbihbjwvw.dv.googlehosted.com."

  icloudDkimRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: sig1._domainkey.bjw.me.uk.
      HostedZoneId: !Ref hostedZone
      Type: CNAME
      TTL: 900
      ResourceRecords:
      - "sig1.dkim.bjw.me.uk.at.icloudmailadmin.com."