Description: "jwilliams.uk domain"
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  hostedZone:
    Type: String
    Description: "Hosted Zone ID"

Resources:

  mxRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: jwilliams.uk.
      HostedZoneId: !Ref hostedZone
      Type: MX
      TTL: 500
      ResourceRecords:
      - "10 mx01.mail.icloud.com."
      - "20 mx02.mail.icloud.com."

  caaRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: jwilliams.uk.
      HostedZoneId: !Ref hostedZone
      Type: CAA
      TTL: 900
      ResourceRecords:
      - "0 issue \"letsencrypt.org\""
      - "0 issue \"amazon.com\""

  txt1RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: jwilliams.uk.
      HostedZoneId: !Ref hostedZone
      Type: TXT
      TTL: 900
      ResourceRecords:
      - "\"apple-domain=Kt0RN1fofPwkhu1h\""
      - "\"v=spf1 include:icloud.com ~all\""

  txt2RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: _dmarc.jwilliams.uk.
      HostedZoneId: !Ref hostedZone
      Type: TXT
      TTL: 900
      ResourceRecords:
      - "\"v=DMARC1;p=quarantine;pct=100;fo=1\""

  icloudDkimRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: sig1._domainkey.jwilliams.uk.
      HostedZoneId: !Ref hostedZone
      Type: CNAME
      TTL: 900
      ResourceRecords:
      - "sig1.dkim.jwilliams.uk.at.icloudmailadmin.com."