Description: "Home Media"
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MusicBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentTierRule
            Status: Enabled
            Transitions:
            - TransitionInDays: 1
              StorageClass: INTELLIGENT_TIERING
  FamilyVideoBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: IntelligentTierRule
            Status: Enabled
            Transitions:
            - TransitionInDays: 1
              StorageClass: INTELLIGENT_TIERING

Outputs:
  MusicBucketName:
    Value: !Ref MusicBucket
    Description: Name of the S3 bucket for holding music files
  FamilyVideoBucketName:
    Value: !Ref FamilyVideoBucket
    Description: Name of the S3 bucket for holding family video files
